import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@repo/ui/globals.css";
import { ApplicationProviders } from "@/providers/app-providers";
import Appbar from "@/components/appbar";
import { cn } from "@repo/ui/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}>
        <ApplicationProviders>
          <Appbar />
          {children}
        </ApplicationProviders>
      </body>
    </html>
  );
}
